### PR TITLE
Update CHRONO_DATA_DIR

### PR DESCRIPTION
**Pull request by HankelBao**
get CHRONOR_DATA_DIR through CONDA_PREFIX to avoid extra export

### CODE REVIEW

**Comment by HankelBao** [comment]
I later find some special cases with MacOS. It is only tested on Archlinux.
Probably more workaround is needed for MacOS.

**Comment by AaronYoung5** [comment]
The conda build on mac always throws a segmentation fault, so I'm building from source outside of anaconda. Is there a way that you can check if you're on a conda env and then use either the CONDA_PREFIX or CHRONO_DATA_DIR depending on that result?

**Comment by HankelBao** [comment]
I think this could be achieve by trying to find the CONDA_PREFIX environment variable.
I would later testify if it works on Xiaohan's Macbook Air.

**Comment by HankelBao** [comment]
I think it works on both Windows/Linux and MacOS now.

**Comment by AaronYoung5** [comment]
Thanks a lot, Hankel!

**Pull request merged**
